### Create branch
POST http://localhost:8000/api/branch/
Content-Type: application/json

{
    "name": "003",
    "address": "Tran Hung Dao"
}

### Get branches
GET http://localhost:8000/api/branch

### Get branch
GET http://localhost:8000/api/branch/1
