### Create an employee
POST http://localhost:8000/api/employee
Content-Type: application/json

{
    "name": "janna",
    "email": "janna@gmail.com",
    "password": "jannajanna",
    "password_confirmation": "jannajanna",
    "branch_id": 6,
    "roles": ["manage", "import"]
}

### Get all employees
GET http://localhost:8000/api/employee

### Get an employee
GET http://localhost:8000/api/employee/5

### Get me
GET http://localhost:8000/api/employee/me

### Login
POST http://localhost:8000/api/employee/login
Content-Type: application/json

{
    "email": "john@gmail.com",
    "password": "johnjohn"
}

### Logout
POST http://localhost:8000/api/employee/logout

### Transfer
POST http://localhost:8000/api/employee/transfer
Content-Type: application/json

{
    "employee_id": 2,
    "branch_id": 7,
    "roles": ["manage", "import"]
}
