### Store Registration
POST http://localhost:8000/api/store/register
Content-Type: application/json

{
    "name": "Hexagon",
    "email": "hexagon@gmail.com",
    "password": "hexagon",
    "password_confirmation": "hexagon",
    "remember": true
}

### Store Login
POST http://localhost:8000/api/store/login
Content-Type: application/json

{
    "email": "hexagon@gmail.com",
    "password": "hexagon",
    "remember": true
}

### Store Logout
POST http://localhost:8000/api/store/logout

### Store Info
GET http://localhost:8000/api/store/me
